### ISSUE TITLE
Consulta sobre practica

### ISSUE THREAD

**Issue by Ivan-Garcia02** [ULL-MII-SYTWS-2425/github-campus-expert-ivan-garcia-gonzalez-alu0101388786#3]
@crguezl 
Hola veo que en la practica esta tengo un INSUFISIENTE, quería preguntar un poco que debo hacer. Viendo de nuevo, debo ir poniendo en el informe pantallazos de lo que fui haciendo en la practica? Además quería preguntar si se considera terminada la practica cuando se marca en el board o al entregar en el campus, y también si debo crear un issues cuando acabe cada practica?

**Comment by crguezl** [comment]
@Ivan-Garcia02 

Cambia las imágenes de Helena por las tuyas. Añade alguna en que se vea que se ha instalado 
[GitHub CLI](https://github.com/cli/cli#installation).

Haz una incidencia cuando lo tengas.

**Comment by Ivan-Garcia02** [comment]
@crguezl 
Buenas, okey ya entendí y cambie las imágenes del README y añadí alguna usando GitHub CLI, gracias.
